development: &default

  # Credentials for REST APIs
  client_id: Ac-P5DJ0jhqBFT2m5OF7lbrkn8wHXw8cn6_kZuR1OrOnHjbOkiBcLqo8iXZgNl4nUh5HHpSe_CMkWMeO
  client_secret: ELTDbykWwDvEK1BUvDqyVDBLtfkep3vzAPtOqKxny3Ha18m7Xuc3xlyZ4yLONRcoyDk8stybg-9xIWEf

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  # app_id: APP-80W284485P519543T
  # username: jb-us-seller_api1.paypal.com
  # password: WX4WTU3S8MY44S7F
  # signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: jv.vargass-facilitator@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

test:
  <<: *default

production:
  <<: *default
  mode: live
